language: go

go:
 - 1.12

env:
 - GO111MODULE=on

before_install:
 - sudo apt-get install -y libopenal-dev

before_script:
 - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
 - go build -tags noaudio ./...
 - go test -tags noaudio ./...
 - fossa init --include-all
 - fossa analyze